# Week 2
## Part 2: NumPy
NumPy is a Python module designed for scientific computation. NumPy has several very useful features. NumPy also provides many useful tools to help you perform linear algebra, generate random numbers and much, much more. More information about [numpy](numpy.org).
### 2.1 Introduction to NumPy Arrays
NumPy arrays are an additional data type provided by NumPy, and they are used for representing *vectors and matrices*. NumPy arrays are n-dimensional array objects and they are a core component of scientific and numerical computation in Python.

Unlike dynamically growing Python lists, NumPy arrays have a ***size that is fixed*** when they are constructed. ***Elements of NumPy arrays are also all of the same data type*** leading to more efficient and simpler code than using Python's standard data types. By default, the elements are floating point numbers.

We can also construct NumPy arrays using specified values, in which case, we use the np.array function, and the input argument to the function is a sequence of numbers, typically a list of numbers.

In [44]:
# Example 1
import numpy as np

print("Using zeros function in numpy")
# Create a vector has 5 elements are zero
zero_vetor = np.zeros(5)
print(zero_vetor)

# Create a matrix has 5 rows, 3 column are zero
zero_matrix = np.zeros((5,3))
print(zero_matrix)

print("Using ones function in numpy")
# Create a vector has 5 elements are one
one_vector = np.ones(5)
print(one_vector)

# Create a empty matrix without initialize
empty_matrix = np.empty((2,3))
print(empty_matrix)

print("Create an array with specific number")
# Create an array with specific value
x = [1,2,3,4]
y = [2,4,6,8]
x_vector = np.array(x)
y_vector = np.array(y)

print(x_vector)
print(y_vector)

# Create an matrix
X = np.array([[1,2,3],[4,5,6]])
print(X)

# Transpose the matrix X
print("Transpose a matrix")
print(X.transpose())

Using zeros function in numpy
[ 0.  0.  0.  0.  0.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Using ones function in numpy
[ 1.  1.  1.  1.  1.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
Create an array with specific number
[1 2 3 4]
[2 4 6 8]
[[1 2 3]
 [4 5 6]]
Transpose a matrix
[[1 4]
 [2 5]
 [3 6]]


### 2.2 Slicing NumPy Arrays
It's easy to index and slice NumPy arrays regardless of their dimension, meaning whether they are vectors or matrices. With one-dimension arrays, we can ***index a given element by its position***, keeping in mind that indices start at 0.

With two-dimensional arrays, ***the first index specifies the row of the array*** and ***the second index specifies the column of the array***. This is exactly the way we would index elements of a matrix in linear algebra.

We can also slice NumPy arrays. Remember the indexing logic. Start index is included but stop index is not, meaning that Python stops before it hits the stop index.

With multi-dimensional arrays, you can use the ***colon character in place of a fixed value for an index***, which means that the array elements corresponding to all values of that particular index will be returned.



In [45]:
import numpy as np

x = np.array([1,3,5])
y = np.array([2,4,6])

X = np.array([[1,2,3],[4,5,6]])
Y = np.array([[2,4,6],[1,3,5]])

# Vector and matrix
print("Vector x", x)
print("Vector y", y)
print("Matrix X:")
print(X)
print("Matrix Y:")
print(Y)

# Access single element in array
print("3rd element in vector x x[2]:", x[2])

# Access the column
print("The first colum of matrix X X[:,0]:")
print(X[:,0])

# Access the row
print("The first row of matrix Y Y[0,:]:")
print(Y[0,:])

# Slicing the array
print("Slicing array from 0 to 2 of y, y[0:2]")
print(y[0:2])

# Add 2 array
z = x+y
print("Adding 2 arrays")
print(z)

# Add 2 columns or rows
print("Adding 2 columns at 3rd")
print(Y[:,2]+X[:,2])
print("Adding 2 rows at 2nd")
print(Y[1,:]+X[1,:])

# Attention
print("Adding 2 lists [2,3]+[4,5]->", [2,3]+[4,5])
print("Adding 2 arrays np.array([2,3]) + np.array([4,5]) ->", np.array([2,3])+np.array([4,5]))

Vector x [1 3 5]
Vector y [2 4 6]
Matrix X:
[[1 2 3]
 [4 5 6]]
Matrix Y:
[[2 4 6]
 [1 3 5]]
3rd element in vector x x[2]: 5
The first colum of matrix X X[:,0]:
[1 4]
The first row of matrix Y Y[0,:]:
[2 4 6]
Slicing array from 0 to 2 of y, y[0:2]
[2 4]
Adding 2 arrays
[ 3  7 11]
Adding 2 columns at 3rd
[ 9 11]
Adding 2 rows at 2nd
[ 5  8 11]
Adding 2 lists [2,3]+[4,5]-> [2, 3, 4, 5]
Adding 2 arrays np.array([2,3]) + np.array([4,5]) -> [6 8]


### 2.3 Indexing NumPy Arrays
* NumPy arrays can also be indexed with other arrays or other sequence-like objects like lists.

In [46]:
z1 = np.array([1,3,5,7,9])
z2 = z1+1
print("z1 ->", z1)
print("z2 ->", z2)

ind=[0,2,3]
print("value with index is a list", z1[ind])
print("value with index is a array", z1[np.array(ind)])

z1 -> [1 3 5 7 9]
z2 -> [ 2  4  6  8 10]
value with index is a list [1 5 7]
value with index is a array [1 5 7]


* NumPy arrays can also be indexed using logical indices.

In [47]:
import numpy as np
z1 = np.array([1,3,5,7,9])

ind = z1>6
print("index boolean", ind)
print("value in z1 that greater 6", z1[ind])

index boolean [False False False  True  True]
value in z1 that greater 6 [7 9]


* When you slice an array using the colon operator, you get a view of the object. This means that if you modify it, the original array will also be modified. This is in contrast with what happens when you index an array, in which case what is returned to you is a copy of the original data.

**In summary, for all cases of indexed arrays, what is returned is a copy of the original data, not a view as one gets for slices.**

In [48]:
# Example using slicing approach
import numpy as np
z1 = np.array([1,3,5,7,9])

# Create an array by sliding the z1
w = z1[0:2]
# Modify the first value
w[0] = 2

print("Value of w", w)
print("Value of z1 changes")
print("Value of z1", z1)

Value of w [2 3]
Value of z1 changes
Value of z1 [2 3 5 7 9]


In [49]:
# Example using index array approach
import numpy as np
z1 = np.array([1,3,5,7,9])

# Create an array by using index
ind = np.array([0,1,2])
w = z1[ind]
# Modify the first value
w[0] = 2

print("Value of w", w)
print("Value of z1 doesn't change")
print("Value of z1", z1)

Value of w [2 3 5]
Value of z1 doesn't change
Value of z1 [1 3 5 7 9]


### 2.4 Building and Examining NumPy Arrays
NumPy provides a couple of ways to construct arrays with fixed, start, and end values, such that the other elements are uniformly spaced between them. 
 * To construct a linearly spaced array element, NumPy provide **linspace** function.
 * To construct a logarithmically spaced array element, NumPy provide **logspace** function. *(first argument that goes into logspace is going to be the log of the starting point. The second argument is log of the endpoint of the array. And the third argument as before, is the number of elements in our array.)*

In [50]:
# Example 1
import numpy as np

# Create a linear space array -> starting point:0, ending point:100, number of points: 20
linear_array = np.linspace(1,100,20)
print("Linear array with starting point:0, ending point:100, number of points:20")
print(linear_array)

# Create a log space element array -> starting point is 10 -> log(10)=1, ending point is 100 -> log(100)=2
logarit_array = np.logspace(1,2, 10)
print("Logarit array with starting point:10, ending point:100, number of points:10")
print(logarit_array)

Linear array with starting point:0, ending point:100, number of points:20
[   1.            6.21052632   11.42105263   16.63157895   21.84210526
   27.05263158   32.26315789   37.47368421   42.68421053   47.89473684
   53.10526316   58.31578947   63.52631579   68.73684211   73.94736842
   79.15789474   84.36842105   89.57894737   94.78947368  100.        ]
Logarit array with starting point:10, ending point:100, number of points:10
[  10.           12.91549665   16.68100537   21.5443469    27.82559402
   35.93813664   46.41588834   59.94842503   77.42636827  100.        ]


In [51]:
# Example2: Construct array of ten logarithmically spaced elements between numbers say 250 and 500. 
import numpy as np
array_log = np.logspace(np.log10(250), np.log10(500), 10)
print(array_log)

[ 250.          270.01493472  291.63225989  314.98026247  340.19750004
  367.43362307  396.85026299  428.62199143  462.93735614  500.        ]


Often we need to know ***the shape of an array or the number of elements in an array***. You can check the shape of an array using shape. Using **shape and size** attributes *(not methods of the arrays.)*

In [52]:
# Example 3:
import numpy as np

X = np.array([[1,2,3],[7,8,9]])
print("Shape of array", X.shape)
print("Size of array ~ Number of element in array:", X.size)

Shape of array (2, 3)
Size of array ~ Number of element in array: 6


* NumPy has its own random module. And in this case, we're going to be generating 10 random numbers drawn from the standard uniform distribution, meaning from the interval from 0 to 1.

In [53]:
# Example 4:
import numpy as np

x_random = np.random.random(10)
print("x random")
print(x_random)
print("Any value in x_random > 0.9", np.any(x_random>0.9))
print("All value in x_random > 0.1", np.all(x_random>0.1))

x random
[ 0.02171387  0.34443211  0.26453677  0.32079737  0.93452337  0.92240021
  0.17435047  0.7667911   0.28433182  0.86428484]
Any value in x_random > 0.9 True
All value in x_random > 0.1 False
